✨ `git_repositories`: add `zoxide` integration
friedow/centerpiece pull request #111
Opened 2024-03-29 22:36 UTC by a-kenji

Add `zoxide` integration for the `git_repositories` plugin. If enabled and installed will sort the paths by their `zoxide` score.

2024-03-30 09:44 UTC, friedow commented on client/src/plugin/git_repositories.rs
> +}
At this point we should probably extract sort to be a function on the Plugin trait which you can override. This would avoid overriding the whole search function here. What do you think?

2024-03-30 10:05 UTC, a-kenji commented on client/src/plugin/git_repositories.rs
> +}
Agreed. I had the same thought when implementing this.
Do you think it makes sense to include, or rather as a different PR?
Since the commits are squashed I'd lean towards a different PR.

2024-03-30 20:28 UTC, friedow commented on client/src/plugin/git_repositories.rs
> +}
You can just include it if you want to do it :)

2024-04-02 20:29 UTC, friedow requested changes

2024-04-02 20:29 UTC, friedow commented on client/src/plugin/git_repositories.rs
> +        });
```suggestion
        scored_entries.sort_by_key(|(_, score)| score);
```

2024-04-02 20:29 UTC, friedow commented on client/src/plugin/git_repositories.rs
> +        }
Please move this to the sorting function.

2024-04-03 17:27 UTC, friedow approved these changes
LGTM

2024-04-03 18:09 UTC, merged