Allow setting colors via configuration
friedow/centerpiece pull request #141
Opened 2024-05-16 15:04 UTC by pinpox

Partly Fixes #108 

I implemented basic color settings trying to follow the other settings. Since I havn't worked with this very much before, I'm sure there is stuff I missed or should be done differently. Please let me know what has to change, any hints very welcome. 

I only implemented colors for now. Not sure if font settings should be a separate PR.

2024-05-17 08:02 UTC, friedow requested changes

2024-05-17 08:02 UTC, friedow commented on client/src/main.rs
> +        let hex_col = HexColor::parse(color).unwrap();
Unwrapping this here is an unsafe action which could terminate the application. It is fair to terminate the application in case of a wrong configuration. However, this should happen at startup time and with a proper error message.

Please add a proper error message if the parsing failed before unwrapping this value.

2024-05-17 09:42 UTC, pinpox commented on client/src/main.rs
> +        let hex_col = HexColor::parse(color).unwrap();
@friedow Thanks for the review! I added an error message here, there is still an issue though (marked with "TODO") in this function: The alpha value of the hex code is not used, because I couldn't figure out how to convert it correctly. Any ideas?

Also, is the error message enough or should I do anything else so that the parsing happens at startup?

2024-05-17 18:04 UTC, friedow commented on client/src/main.rs
> +        let hex_col = HexColor::parse(color).unwrap();
Looks good to me! No need to adjust this further. 

My best guess right now is try: `hex_col.a as f32`. I can't try it myself right now because I'm on holidays and don't have a laptop on me 😅. If that does not work I can try to help with that on Monday :).

2024-05-18 07:07 UTC, friedow commented on client/src/main.rs
> +        let hex_col = HexColor::parse(color).unwrap();
Ah, I just thought about this again. The conversion does what it's supposed and we don't get a compilation error anymore because the types are correct. But the `hex_col.a` value is probably on a scale from 0-255 and the iced color wants an alpha value on a scale of 0-1. 
I'll check the docs on this on Monday and will also test this :).

2024-05-21 19:28 UTC, a-kenji commented
Good job @pinpox! You can run the formatter toolchain in the project with:
```
nix fmt
```

2024-05-23 06:21 UTC, friedow requested changes
There are also a few color values still hardcoded which should be changed as well.
**text:**
- https://github.com/friedow/centerpiece/blob/main/client/src/component/entry.rs#L48
- https://github.com/friedow/centerpiece/blob/main/client/src/component/query_input.rs#L56

**surface:**
- https://github.com/friedow/centerpiece/blob/main/client/src/component/query_input.rs#L52
- https://github.com/friedow/centerpiece/blob/main/client/src/component/query_input.rs#L60
- https://github.com/friedow/centerpiece/blob/main/client/src/component/query_input.rs#L64

2024-05-23 06:21 UTC, friedow commented on client/src/main.rs
> +    iced::Color::from_rgba8(hex_col.r, hex_col.g, hex_col.b, hex_col.a as f32)
```suggestion
    iced::Color::from_rgba8(hex_col.r, hex_col.g, hex_col.b, (hex_col.a as f32) / 255.0)
```

2024-05-23 06:21 UTC, friedow commented on client/src/settings.rs
> +            surface: "#00000033".to_string(),
```suggestion
            text: "#ffffff".to_string(),
            background: "#000000".to_string(),
            surface: "#ffffff22".to_string(),

```

2024-05-23 09:27 UTC, pinpox commented
@friedow Updated the missing colors. I also moved the `hexcolor` helper function to `settings.rs` so I don't have to define it every time. Let me know if that is not the right place for it. 

Maybe it would make sense to apply the `hexcolor()` just one time on startup when reading all the settings form the file and have the color settings be a global that is already of the type `iced::Color` and can referenced?

2024-05-23 17:34 UTC, friedow commented
You'll need to run the formatter again :)

2024-05-23 18:17 UTC, friedow approved these changes

2024-05-23 18:17 UTC, merged

2024-07-02 19:48 UTC, thangisme commented
So how do I set custom color now? 
I tried this in config :
```
color: 
  background: "#11111b"
  foreground: "#cdd6f4"
```
It didnt work